### ISSUE TITLE
no ad 

### ISSUE THREAD

**Issue by OdaiTu** [alaborderie/ng2-ad-dfp#1]
thank you for this great component 
i have done just like you did but no ad shows in my app
i added the script in the index.html
and make my settings like 'assets/settings/settings.json'

and added the tag in my component
here is the code

![image](https://user-images.githubusercontent.com/12837840/29164426-04773160-7dc8-11e7-95e5-a32d96afcf1e.png)

![image](https://user-images.githubusercontent.com/12837840/29164457-1ac935a8-7dc8-11e7-9615-03660e985e43.png)

![image](https://user-images.githubusercontent.com/12837840/29164470-28a95b94-7dc8-11e7-8d7e-d484de43423d.png)

![image](https://user-images.githubusercontent.com/12837840/29164486-32e40c3a-7dc8-11e7-89bd-25d78554e26f.png)

**Comment by OdaiTu** [comment]
i think the problem in settings.json file ?

**Comment by OdaiTu** [comment]
sorry
i have updated my json file  but new error in the console

![image](https://user-images.githubusercontent.com/12837840/29165694-4e2bf04e-7dcc-11e7-9923-4d86f179b354.png)

**Comment by alaborderie** [comment]
Your settings file is wrong. You need to adjust a few things.

`network` is your network ID. You can get it on DFP on the top right of your screen, under your e-mail address...

`tags` is actually the unique number of your ad. In `div-gpt-ad-1502269498848-0` the ID of your banner is `1502269498848`

`ID` is the Code of your ad. You get it in the Inventory tab of DFP. One of mines look like that:
<img width="1210" alt="screen shot 2017-08-13 at 22 01 48" src="https://user-images.githubusercontent.com/26012730/29253011-5bd85fda-8073-11e7-8088-d08746e46aa2.png">


The error you're getting tells you DoubleClick threw an error, which means your configuration files are wrong.

I hope it helped you and am waiting for an answer from you ;)

**Comment by OdaiTu** [comment]
@alaborderie 

thank you for your time sir
i just doing like you wrote but still not show

when i inspect the ad i found this
![image](https://user-images.githubusercontent.com/12837840/29264255-fe76b2b6-80e4-11e7-96ac-2029c0cb6640.png)


here is the settings json too

![image](https://user-images.githubusercontent.com/12837840/29264276-1179266e-80e5-11e7-9c8c-6d0c2cf3ac55.png)


and here is the ad unit !

`<script>
            googletag.cmd.push(function() {
                googletag.defineSlot('/95961110/4', [728, 90], 'div-gpt-ad-1502622550514-0').addService(googletag.pubads());
                googletag.pubads().enableSingleRequest();
                googletag.enableServices();
            });
            </script>`

**Comment by OdaiTu** [comment]
@alaborderie

**Comment by alaborderie** [comment]
Sorry I could not answer before. Currently on my phone so forgive my typing skills :)

The "ID" of your banner should be the code on DFP. Please check the screenshot I sent you again. For me `tags` was some random number like you and `ID` is `1`.

If you can inspect and find the ad but it's not showing up, it means DFP is looking for an Ad that does not exist. It's most likely that your Tag or ID has a typo or is wrong...

Thanks for the feedback and sorry again about the delay!

Let me know if it's working properly! ;)

**Comment by OdaiTu** [comment]
@alaborderie 
thank you again for your time
its work properly now 👍 

but i cant use it for online because the aot error :(

**Comment by alaborderie** [comment]
Nice! I'll check it out tomorrow ;)!
