### ISSUE TITLE
aot error

### ISSUE THREAD

**Issue by OdaiTu** [alaborderie/ng2-ad-dfp#2]
![image](https://user-images.githubusercontent.com/12837840/29167835-c07ae8b4-7dd4-11e7-9e49-c499f2827749.png)

this error witn doning ng build --prod --aot

**Comment by alaborderie** [comment]
I really do not know about this one and will definitely try to make it work asap 🙂
Thanks for the issue!

**Comment by OdaiTu** [comment]
@alaborderie 
thank you

**Comment by alaborderie** [comment]
Giving you and update:

I probably forgot to do something when I made the library "statically analyzable for AoT"...

I'll try to update my library following this [Medium](https://blog.angularindepth.com/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5).

Thanks again for the issue :D!

**Comment by OdaiTu** [comment]
thank you @alaborderie 
let me know when its done plz

**Comment by alaborderie** [comment]
Update to 1.2.7, it is already published 🙂

**Comment by OdaiTu** [comment]
@alaborderie  thank you again

look at this error when updated

![image](https://user-images.githubusercontent.com/12837840/29412099-fecf9dc2-835f-11e7-8e22-f1999722372e.png)

**Comment by alaborderie** [comment]
Oh terrible mistake from me, i'll publish a new one in a few minutes !

**Comment by alaborderie** [comment]
Okay, so as I could not publish over 1.2.7, a new version 1.2.8 has been published.

Can you please update again and tell me if that is working? Thanks you ;)

**Comment by OdaiTu** [comment]
@alaborderie  thank you for your time bro i know i have take aot of your time
but here is another error when aot 

see

![image](https://user-images.githubusercontent.com/12837840/29421193-f7169ca8-837c-11e7-8d3a-1e9865c41fe6.png)

**Comment by alaborderie** [comment]
I'm pretty sure it's something about `tsconfig.json`. The one used for ng2-ad-dfp is like this:
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "removeComments": true,
    "sourceMap": true,
    "outDir": "bundle",
    "declaration": true
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true
  },
  "files": [
    "src/ad-dfp.ts"
  ],
  "exclude": [
    "node_modules/*"
  ]
}
```

Maybe yours is different and UglifyJS cannot parse my module like it should...

I'll investigate asap 😄

**Comment by OdaiTu** [comment]
@alaborderie  Thank You again ! and for loop of thanks to you hhh :)
im waiting bro

**Comment by OdaiTu** [comment]
what happen with you friend ! 
@alaborderie

**Comment by alaborderie** [comment]
I can't find a solution for this one yet and I have other things to do during the day at my job... Sorry but you'll have to wait or figure out yourself ! :/
I'm still working on it, but it will maybe take time...

**Comment by OdaiTu** [comment]
@alaborderie 
thank you again and again im sorry
take your time bro :)
all the respect .

**Comment by alaborderie** [comment]
It's fine you're helping me! I had no idea such problems were occuring when using AoT 🙂

**Comment by alaborderie** [comment]
Okay keeping you update @OdaiTu...

I'm having another issue but compiling works fine now ;)!
I'm trying to get this fixed soon.

**Comment by alaborderie** [comment]
@OdaiTu could you try again using `ng2-ad-dfp@1.2.9` please ? Works fine on my computer using `ng build -prod -aot` :)

**Comment by OdaiTu** [comment]
@alaborderie 
its worked like a charm Thanks alot !

**Comment by alaborderie** [comment]
Glad to hear it works fine 🙂
