### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by kjimenezdev** [alaborderie/ng2-ad-dfp#3]
Hi do you have any usage-example source code?

Thanks in advance.

**Comment by alaborderie** [comment]
Sorry about the delay ! I should probably create a "Sample" Project...
I'm busy these days so I'll juste paste you some code I have on my Ionic 2/3 projects:

### src/index.html
```html
<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>
```

### src/app/app.module.ts
```ts
import { AdDFPComponent } from 'ng2-ad-dfp';

@NgModule({
    declarations: [
        AdDFPComponent
    ]
})
export class AppModule { }
```
### src/assets/settings/settings.json
```json
{
  "network": 000000000,
  "tags": {
    "banner": 1234567891011
  },
  "ID": {
    "banner": "my-banner"
  },
  "mapping": {
    "mobile": {
      "width": 320,
      "height": 50
    },
    "tablet": {
      "width": 728,
      "height": 90
    },
    "desktop": {
      "width": 1024,
      "height": 120
    }
  },
  "adBlockDetector": false
}
```
### src/pages/yourPage/yourPage.html
```html
<ad-dfp [type]="'banner'"></ad-dfp>
```

And voilà, my banner is showing up on my app in yourPage.html 🙂!

I will do a sample project anyway! Thanks!
