### ISSUE TITLE
Ads Not binding

### ISSUE THREAD

**Issue by nidhinprathap** [alaborderie/ng2-ad-dfp#5]
Just started to use the module. Im new to DFP so correct me if wrong.

I was debugging trough the module & got stuck at a place:- 

> if (googletag && googletag.apiReady) {

The field `apiReady` is coming undefined many times.. But if i debug and check the value in callback of below execution

> googletag.cmd.push(function () {

the value is set as true. So when the page loads the `googletag.apiReady` is checked before the googletag is initialised... im not sure whether some configuration i did is causing this or something else

**Comment by alaborderie** [comment]
That is not something I ever encountered so I'll check it out...
I'm sure a lot of optimisation has to be made on this module, thanks for your issue ;)

**Comment by alaborderie** [comment]
Oh right! I just remember that is something I fixed some time ago...
If you are using AoT when building, this `if` statement is always false. I commented it out, but maybe forgot to deploy the new version on npm...

I merged a pull request and am now deploying a new version (1.2.10)

Please run `npm install --save ng2-ad-dfp@latest` and check that v1.2.10 has been installed
Tell me if it's fixed or not :) !

**Comment by nidhinprathap** [comment]
```
core.js:1448 ERROR TypeError: Cannot read property 'push' of undefined
    at AdDFPComponent.displayAd (ad-dfp.js:49)
    at SafeSubscriber.eval [as _next] (ad-dfp.js:19)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:240)
    at SafeSubscriber.next (Subscriber.js:187)
    at Subscriber._next (Subscriber.js:128)
    at Subscriber.next (Subscriber.js:92)
    at XMLHttpRequest.onLoad (http.js:1591)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4736)
    at ZoneDelegate.invokeTask (zone.js:420)
```

Now im getting this error .. Just updated to latest ng2-ad-dfp

**Comment by nidhinprathap** [comment]
Its like the googletag object gets called before the js file is lodaed.. just a gues

**Comment by alaborderie** [comment]
It's probably what is happening... Reading the code there is no verification that gpt.js from google is loaded before.

I think I will refacto the whole module but I do not have time to do it today... Sorry ! Maybe tomorrow

Thanks for the issue, I'll work on it asap ;)

**Comment by nidhinprathap** [comment]
Ok Thanks will check back tomorrow

**Comment by alaborderie** [comment]
I think this is fixed... It's working as expected on all of my projects, and when I deliberately make `googletag` value be `undefined` it's not crashing anymore. (But ad not showing)

Let me know if `1.2.11` fixed it for you or not! Thanks!
