### ISSUE TITLE
Can't setup ads

### ISSUE THREAD

**Issue by hoangbk009** [alaborderie/ng2-ad-dfp#7]
hi @alaborderie 
i can't setup ads
my website: https://staging.topical.jp

my config:
http://prntscr.com/lhaxch
http://prntscr.com/lhay5w
http://prntscr.com/lhaz5p
```
{
  "network": 22524478,
  "tags": {
    "banner": 1492748221001,
    "inter": "00000000"
  },
  "ID": {
    "banner": "SSI_SP_300_250",
    "inter": " "
  },
  "mapping": {
    "mobile": {
      "width": 320,
      "height": 250
    },
    "tablet": {
      "width": 320,
      "height": 250
    },
    "desktop": {
      "width": 320,
      "height": 250
    }
  },
  "adBlockDetector": false
}
```

**Comment by alaborderie** [comment]
Hi @hapo-hoangnh!
It looks like the ad is not loaded, but the frame is correctly created in your DOM.

You'll have more luck on Google's forum or StackOverflow as the problem doesn't come from my library, and I don't have the knowledge to help you there... I never encountered this problem on my projects.

Your console returns a 400 CORS error which probably means there is a problem in your google doubleclick for publishers account set-up...

Good luck :) !

**Comment by alaborderie** [comment]
Hi @hapo-hoangnh !!

I'm happy to tell you that I just released a new version of the library!

It's now under the name of ngx-ad-dfp and you can check it [here](https://github.com/alaborderie/ngx-ad-dfp)!

It's now also easier to use :) feel free to give it a try
